name: Commitlint PR Title

on:
  pull_request:
    types: [opened, labeled, unlabeled, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - id: pr-lint
        uses: livingbio/pr-lint@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          pr_number: ${{ github.event.number }}
