name: Commitlint PR Title

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pr-lint
        run: pip install pr-lint

      - name: Run Commitlint on PR title
        run: pr-lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
